export const GET_ALL_EMOJIS = "GET_ALL_EMOJIS";
export const GET_CATEGORY_EMOJIS = "GET_CATEGORY_EMOJIS";
export const GET_INITIAL_STATE = "GET_INITIAL_STATE";
export const GET_EMOJIS_FOR_SEARCH = "GET_EMOJIS_FOR_SEARCH";
